### ISSUE TITLE
Add repeatedly.once?

### ISSUE THREAD

**Issue by julywind168** [lpil/repeatedly#2]
This is a common requirement。

**Comment by lpil** [comment]
What would that function do?

**Comment by julywind168** [comment]
> 这个函数起什么作用？

Automatically destroyed after one execution, similar to timeout

**Comment by lpil** [comment]
Isn't that just calling your function directly?

**Comment by julywind168** [comment]
> Isn't that just calling your function directly?

I use repeatedly as timer inside the actor.
for example:
```gleam
let repeater = repeatedly.call(500, Nil, fn(_, i) {
    io.println("Do something once")
    repeatedly.stop(actor_state.repeater)
})

// set repeater to actor state
ActorState(..state, repeater:repeater)
```
Can we have an additional API like this
```gleam
let _ = repeatedly.call_once(500, Nil, fn(_, i) {
    io.println("Do something once")
})
```

**Comment by lpil** [comment]
Sorry, I'm not understanding. Why are you calling the function inside `repeatedly.call` and then stopping immediately?

**Comment by julywind168** [comment]
> Sorry, I'm not understanding. Why are you calling the function inside `repeatedly.call` and then stopping immediately?

in game room actor, has some robot player, it simulate human action delay some second

**Comment by lpil** [comment]
I would spawn a new process and sleep it for that. Something like this:

```gleam
process.start(fn() {
  process.sleep(1000)
  io.println("Do something once")
}, True)
```

You may also consider using the `send_after` function, depending on your specific situation.

This library is for calling functions repeatedly, so that function is not suitable for this library. Thank you for the suggestion though!

**Comment by julywind168** [comment]
> I would spawn a new process and sleep it for that. Something like this:
> 
> ```gleam
> process.start(fn() {
>   process.sleep(1000)
>   io.println("Do something once")
> }, True)
> ```
> 
> You may also consider using the `send_after` function, depending on your specific situation.
> 
> This library is for calling functions repeatedly, so that function is not suitable for this library. Thank you for the suggestion though!

Okay, I know about this plan, but it cannot be cancelled. Perhaps I will create a timer library for games in the future, thank you

**Comment by lpil** [comment]
You can cancel the timers used with `send_after`, that may be useful for you
